name: Multi Platform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ubuntu-job:
    name: Ubuntu Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Ubuntu System Info
        run: uname -a

      - name: Create and Read Ubuntu File
        run: |
          echo "This file was created on Ubuntu" > ubuntu-file.txt
          cat ubuntu-file.txt

  windows-job:
    name: Windows Job
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Windows System Info
        run: systeminfo

      - name: Create and Read Windows File
        run: |
          echo "This file was created on Windows" > windows-file.txt
          type windows-file.txt

  macos-job:
    name: macOS Job
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print macOS System Info
        run: uname -a

      - name: Create and Read macOS File
        run: |
          echo "This file was created on macOS" > macos-file.txt
          cat macos-file.txt
